title: my github.io blog
email: george.toothman@gmail.com
description: A Weblog with posts ranging in subject from Ruby methods to Rails Apps and more.  
baseurl: ""
url: "https://georgetoothman.github.io"
twitter_username: georgetoothman
github_username:  georgetoothman
markdown: kramdown
gems:
  - jekyll-seo-tag
