title: http://cantate.co
email: get@cantate dot co
description: > # this means to ignore newlines until "baseurl:"
	This blog is part of an ambitious project defining the next 
	version of the World Wide Web. I write here, and work there ~>
	Cantate Dot Co., Inc. 
baseurl: ""
url: "http://georgetoothman.github.io"
twitter_username: georgetoothman
github_username:  georgetoothman
markdown: kramdown
gems:
  - jekyll-seo-tag
