title: Web 3 Dot 0
email: get@cantate.co
description: 
baseurl: ""
url: "https://georgetoothman.github.io"
twitter_username: georgetoothman
github_username:  georgetoothman
markdown: kramdown
gems:
  - jekyll-seo-tag
