title: Web 3 Dot 0
email: get@cantate.co
description: > # this means to ignore newlines until "baseurl:"
	Suppose that the second evolutionary stage of the World Wide Web was called *web two point zero*. This is my blog, **Web 3 Dot 0**; a simple, scrolling version of my thoughts. For professional related inquiries, reroute to www.cantate.co/contact.
baseurl: ""
url: "http://georgetoothman.github.io"
twitter_username: georgetoothman
github_username:  georgetoothman
markdown: kramdown
gems:
  - jekyll-seo-tag
